# Notes from PyTorch Official Documentation's 60 Minute Blitz

In [2]:
import torch
import numpy as np

### Tensor initialization

In [10]:
# Tensor initialization: array, numpy arrays, another tensor
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
# Can also be initialized with a shape
shape = (2, 3)
rand_tensor = torch.rand(shape) # [0, 1)
print(rand_tensor)

ones_tensor = torch.ones(shape) # uses torch.set_default_dtype; default is float32
print(ones_tensor)

tensor([[0.6776, 0.2127, 0.1208],
        [0.1358, 0.1509, 0.8340]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.float32

### Tensor Attributes

In [19]:
tensor = torch.rand(shape)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([2, 3])
torch.float32
cpu


### Tensor Operations

In [ ]:
# NumPy indexing/slicing


False